site_name: Smoldyn

theme: 
    name: material

repo_url: https://github.com/dilawar/Smoldyn-official

nav:
    - 'User Guide':
        - 'Introduction' : 'user-guide/index.md'
        - 'Installation' : 'user-guide/installation.md'
        - 'Getting started': 'user-guide/getting-started.md'
        - 'References': 'user-guide/references.md'
        - 'Acknowledgements': 'user-guide/acknowledgement.md'
    - 'Python API':
        - 'User API': 'python-guide/user-api.md'
        - 'Developer API': 'developer-guide/python-api.md'
    - 'Developer Guide':
        - 'About the codebase': 'developer-guide/about-codebase.md'
    - 'Other documents': 'other/emulate-doc.md'

markdown_extensions:
    - toc:
        baselevel: 1
        permalink: True
    - meta
    - codehilite
    - admonition
    - attr_list
    - mkautodoc
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    # - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tabbed
    - pymdownx.tilde

plugins:
    - search
    - mkapi:
        src_dirs: [source/python]

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js
