[package]
name = "smoldyn"
version = "2.27.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4.6.6", features = ["derive"] }
cxx = { version = "1", features = ["c++17"] }
libc = "0.2.189"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[build-dependencies]
cmake = "0.1.58"
cxx-build = "1"
